language: python
python:
  - '2.7'
env:
  global:
    secure: Re8YqE+Brvkr+EA8zKO4dlzvd0gbXjHmtSTXuxM1/35H9zYCi2iVytOfR2I0DtR7pS7ROtqvLYwuMyRXBHdvm/jEUh5GzI5rvrMjpbwW2k02Y/2Uj4wdgh4BgU2NTCyeKNMTlaBNrxD9pJdDOtvGVWF89q4gte6E65IHWhXbfzzT7Rui9NLTq9VYj7OFvL+2Bb7s8v8pUp80uVC14VSX+VJrfnBS7xVU9m119DF6mH6w/53J3gx4qLU6c4Ff0fgKOUzDzR/2ctjjvLRxCNaNZgEGMG6C68vw6V0eU/CR3POojl98xvqmflY+42yTd10EU70l6jxXIQyg8udXiCPdZ5PxTFh8ZnA4R62SnU+q78sXEmiuDcXRklm52Xnm8lMpXJ/htk1ltPWE5NPhsh4aAxWGooy2hYAGcLWKRY4JarGHjlxplsopjcBkqv1xX+5dSZvXartfpTyqG3t7QQtVpKlzLXkZY0wdf3pFpo1Y9D+FC4qBI0ULjIzo6c2NiN/68rrV0BNK3sqFXZByeX+s5nxtcNNir7fB1dpYdOFl/4/Qtw+EEUZt/32ifTNjfYl1vYYrfVI10tEAShvSzBLRlVipLScGzkFX54AegWbtG/9RA1YUXcukWzZTM+EmE6vdxO35ol9RRn9uZQuxmi3VxMnkq9ch8FnJLbySxXtPTnU=
before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install build-essential
  - sudo apt-get install gcc-multilib g++-multilib lib32z1 lib32stdc++6 lib32gcc1 expat:i386 fontconfig:i386 libfreetype6:i386 libexpat1:i386 libc6:i386 libgtk-3-0:i386 libcanberra0:i386 libpng12-0:i386 libice6:i386 libsm6:i386 libncurses5:i386 zlib1g:i386 libx11-6:i386 libxau6:i386 libxdmcp6:i386 libxext6:i386 libxft2:i386 libxrender1:i386 libxt6:i386 libxtst6:i386
install:
  - wget -O sim.tar.gz $SIM_LOCATION
  - tar -zxf sim.tar.gz
  - export PATH=`pwd`/sim/bin:$PATH
  - pip install git+git://github.com/chiggs/fusesoc
  - pip install git+git://github.com/LarsAsplund/vunit
script:
  - python ./run_vunit.py -o packet_generator -x results.xml --log-level debug

